# Run cargo audit once every month and create issues for vulnerabilities found
name: Security Audit

on:
  schedule:
    # Run once every month (first of the month at midnight)
    - cron: '0 0 1 * *'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run cargo audit
        uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

    permissions:
        # to create issues
        issues: write
        # to create check
        checks: write
